# Generated by Django 5.1.2 on 2024-10-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_photos',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Фото'),
        ),
    ]
